name: Publish Packages

on:
  workflow_dispatch:
  push:
    branches:
      - master # Default release branch
    paths:
      - 'src/**'
jobs:
  publish:
   runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
   env:
      Wap_Project_Path: src\HandyExtensions\HandyExtensions.csproj

   steps:
   - uses: cwinland/HandyExtensions/.github/workflows/test.yml@master
   # Nuget        
   - name: Publish NuGet
     uses: brandedoutcast/publish-nuget@v2.5.5
     with:
       PROJECT_FILE_PATH: $env:Wap_Project_Path
       TAG_FORMAT: '*'  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
