name: Publish Packages

on:
  workflow_dispatch:
  push:
    branches:
      - master # Default release branch
    paths:
      - 'src/**'
jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: HandyExtensions.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
      #Test_Project_Path: wpf-material-dialogs.test\wpf-material-dialogs.test.csproj               # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: src    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: src/HandyExtensions.csproj

    steps:

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore and test the application
      uses: cwinland/HandyExtensions/.github/workflows/test.yml@master

    # Nuget        
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: $env:Wap_Project_Path
        TAG_FORMAT: '*'  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
